### ISSUE TITLE
[7.6.1-7.6.2 regression] "Unable to communicate with the parent window" error when opening Dropbox file chooser

### ISSUE THREAD

**Issue by bhagyashri-sawkar** [jiahaog/nativefier#616]
I've integrated Dropbox file chooser in our website. When i try to open the file chooser from nativefier app it gives this error "Unable to communicate with the parent window" as a result the dropbox popup doesn't get closed on file selection.
This was working fine for nativefier version 7.6.1, but not working now for 7.6.2.

This issue can be reproduced using this dropbox file chooser sample site as URL: `https://www.dropbox.com/developers/chooser`

For me this is happening on both Ubuntu & Windows.

Are you nativefying a public website? - yes
Full nativefier command used to build your app: `nativefier https://www.dropbox.com/developers/chooser  --internal-urls .*`
Version of Nativefier (run nativefier --version): 7.6.2
Version of node.js (run node --version): v8.11.1
OS: <Windows 7, Ubuntu 16.04>

**Comment by bacongravy** [comment]
...in which case, it is probably fixed with https://github.com/jiahaog/nativefier/commit/69a5b2cbbe356876b767993358a1806ac6c5695f, which hasn't been released yet.  Might be worth cutting a 7.6.3 release with just that fix (along with a bump to Electron 1.8.7).

**Comment by ronjouch** [comment]
@bacongravy ah, true. I'll release 7.6.3 soon, then; it will have [7.6.2....master](https://github.com/jiahaog/nativefier/compare/v7.6.2...master): your fix, Electron 2.0.2 by default, macOS tabs.

@bhagyashri-sawkar I'll ping you here when 7.6.3 is on npm. In the meantime, if you have the time for that, a test confirming the problem is fixed on master (see [our dev build guide](https://github.com/jiahaog/nativefier/blob/master/docs/development.md#environment-setup)) is welcome.

**Comment by bacongravy** [comment]
Might be worth branching from the 7.6.2 tag and backporting the `.newGuest` fix to put out a 7.6.3.  I had sort of been assuming you'd bump the version to 7.7 or 8.0 to account for the electron 2 dependency update and the new tabs feature.

**Comment by ronjouch** [comment]
@bacongravy afaik, Electron 2.0.0 doesn't change anything to the eyes of a user(and we took care of the deprecations), so semver says it doesn't mandate a major bump. You're right that I could have bumped to 7.7.0 for tabs, though. Whatever, 7.6.3 is released and is on npm.

@bhagyashri-sawkar tests welcome 🙂.

**Comment by bhagyashri-sawkar** [comment]
@ronjouch Thanks for the update. I tested on master as well as on 7.6.3, its still doesn't seem to be working.

**Comment by ronjouch** [comment]
> *"I tested on master as well as on 7.6.3, it still doesn't seem to be working."*

@bacongravy

**Comment by bacongravy** [comment]
That’s disappointing.  I suspect we’ll have to decide between disabling node integration, and having this use case work.  I can try testing that tonight.

**Comment by bhagyashri-sawkar** [comment]
@bacongravy Please let me know when its fixed.

**Comment by bacongravy** [comment]
I wasn't able to review this last night but expect to do so today.

**Comment by bacongravy** [comment]
I've put up a fix in #620. I have verified that it fixes the issue with the Dropbox chooser.
